# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.srcs/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/top_StreamingDataflowPartition_1_0.xci
# IP: The module: 'top_StreamingDataflowPartition_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_wstrm_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_wstrm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_wstrm_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_wstrm_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_wstrm_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_wstrm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_wstrm_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_wstrm_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_wstrm_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_wstrm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_wstrm_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_wstrm_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0} -quiet] -quiet

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0/constraints/StreamingDataflowPartition_1_LabelSelect_hls_0_ooc.xdc

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0/constraints/StreamingDataflowPartition_1_MVAU_hls_2_ooc.xdc

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0/constraints/StreamingDataflowPartition_1_MVAU_hls_1_ooc.xdc

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0/constraints/StreamingDataflowPartition_1_MVAU_hls_0_ooc.xdc

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_StreamingDataflowPartition_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/top_StreamingDataflowPartition_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_StreamingDataflowPartition_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.srcs/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/top_StreamingDataflowPartition_1_0.xci
# IP: The module: 'top_StreamingDataflowPartition_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_wstrm_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_wstrm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_wstrm_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_wstrm_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_wstrm_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_wstrm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_wstrm_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_wstrm_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_wstrm_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_wstrm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_wstrm_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_wstrm_0} -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0 || ORIG_REF_NAME==StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0} -quiet] -quiet

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0/constraints/StreamingDataflowPartition_1_LabelSelect_hls_0_ooc.xdc

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0/constraints/StreamingDataflowPartition_1_MVAU_hls_2_ooc.xdc

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0/constraints/StreamingDataflowPartition_1_MVAU_hls_1_ooc.xdc

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0/constraints/StreamingDataflowPartition_1_MVAU_hls_0_ooc.xdc

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_StreamingDataflowPartition_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/top_StreamingDataflowPartition_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_StreamingDataflowPartition_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
