# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_StreamingDataflowPartition_1_0/top_StreamingDataflowPartition_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_StreamingDataflowPartition_1_0 || ORIG_REF_NAME==top_StreamingDataflowPartition_1_0} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_dma_0_0 || ORIG_REF_NAME==top_axi_dma_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_perf_mon_0_0/top_axi_perf_mon_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_perf_mon_0_0 || ORIG_REF_NAME==top_axi_perf_mon_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_1/top_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xbar_1 || ORIG_REF_NAME==top_xbar_1} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0_axi_periph_0/top_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ps7_0_axi_periph_0 || ORIG_REF_NAME==top_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_100M_0 || ORIG_REF_NAME==top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_2/top_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xbar_2 || ORIG_REF_NAME==top_xbar_2} -quiet] -quiet

# IP: bd/top/ip/top_axi_mem_intercon_0/top_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_mem_intercon_0 || ORIG_REF_NAME==top_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconcat_0_0/top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconcat_0_0 || ORIG_REF_NAME==top_xlconcat_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_1_0/top_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_1_0 || ORIG_REF_NAME==top_xlconstant_1_0} -quiet] -quiet

# IP: bd/top/ip/top_system_ila_0_1/top_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_system_ila_0_1 || ORIG_REF_NAME==top_system_ila_0_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_us_0/top_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_us_0 || ORIG_REF_NAME==top_auto_us_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_us_1/top_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_us_1 || ORIG_REF_NAME==top_auto_us_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_1/top_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_1 || ORIG_REF_NAME==top_auto_pc_1} -quiet] -quiet

# IP: bd/top/ip/top_fifo_interface_0_0/top_fifo_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fifo_interface_0_0 || ORIG_REF_NAME==top_fifo_interface_0_0} -quiet] -quiet

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/top_ooc.xdc
