# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.runs/synth_1/top_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.cache/wt [current_project]
set_property parent.project_path /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths {
  /tmp/finn_dev_lsh/code_gen_ipgen_StreamingDataflowPartition_0_IODMA_hls_0_tgu7ix59/project_StreamingDataflowPartition_0_IODMA_hls_0/sol1/impl/ip
  /home/lsh/Documents/VIVADO/ip_repo
  /home/lsh/Documents/VIVADO/20241206/ip_repo
  /tmp/finn_dev_lsh/vivado_stitch_proj_i5tk9j7c/ip
  /tmp/finn_dev_lsh/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_0_14x995nz/project_StreamingDataflowPartition_1_MVAU_hls_0/sol1/impl/ip
  /tmp/finn_dev_lsh/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_1_50lritfa/project_StreamingDataflowPartition_1_MVAU_hls_1/sol1/impl/ip
  /tmp/finn_dev_lsh/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_2_02djbpo7/project_StreamingDataflowPartition_1_MVAU_hls_2/sol1/impl/ip
  /tmp/finn_dev_lsh/code_gen_ipgen_StreamingDataflowPartition_1_LabelSelect_hls_0_x6g5_c6q/project_StreamingDataflowPartition_1_LabelSelect_hls_0/sol1/impl/ip
  /tmp/finn_dev_lsh/vivado_stitch_proj_x9l2zrw8/ip
  /home/lsh/FPGA/finn/finn-rtllib/memstream
  /tmp/finn_dev_lsh/code_gen_ipgen_StreamingDataflowPartition_2_IODMA_hls_0_tuypk1du/project_StreamingDataflowPartition_2_IODMA_hls_0/sol1/impl/ip
  /tmp/finn_dev_lsh/vivado_stitch_proj_74e2cunt/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.srcs/sources_1/imports/hdl/top_wrapper.v
add_files /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_LabelSelect_hls_0_0/constraints/StreamingDataflowPartition_1_LabelSelect_hls_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0/constraints/StreamingDataflowPartition_1_MVAU_hls_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_1_0/constraints/StreamingDataflowPartition_1_MVAU_hls_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_0_0/constraints/StreamingDataflowPartition_1_MVAU_hls_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/src/StreamingDataflowPartition_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_StreamingDataflowPartition_1_0/top_StreamingDataflowPartition_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_axi_perf_mon_0_0/top_axi_perf_mon_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_axi_perf_mon_0_0/top_axi_perf_mon_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_axi_perf_mon_0_0/top_axi_perf_mon_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_xbar_1/top_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_xbar_2/top_xbar_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/ip/ip_0/bd_c657_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_system_ila_0_1/bd_0/bd_c657_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_system_ila_0_1/top_system_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_auto_pc_0/top_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_auto_us_0/top_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_auto_us_0/top_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_auto_us_0/top_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_auto_us_1/top_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_auto_us_1/top_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_auto_us_1/top_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_auto_pc_1/top_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/top_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.srcs/utils_1/imports/synth_1/top_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_wrapper -part xc7z020clg400-1 -directive AlternateRoutability -global_retiming on -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
