# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.srcs/sources_1/bd/top/ip/top_xbar_2/top_xbar_2.xci
# IP: The module: 'top_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_xbar_2/top_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.srcs/sources_1/bd/top/ip/top_xbar_2/top_xbar_2.xci
# IP: The module: 'top_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsh/2025/vivado_zynq_proj_scw60p79/finn_zynq_link.gen/sources_1/bd/top/ip/top_xbar_2/top_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
